repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
